### ISSUE TITLE
pointData in advection step

### ISSUE THREAD

**Issue by tobre1** [ViennaTools/ViennaLS#57]
Why is the domain meta data cleared before the advection step in line 332 in lsAdvect.hpp?
This removes all point data stored in the lsDomain. Thus the point data will not be carried over in the resulting domain.

Also, in the `rebuildLS` function, where the point data would be transferred to the new lsDomain (line 265), shouldn't it be
```
if (pointData.getScalarDataSize() || pointData.getVectorDataSize())
```
so that it executes if scalar data or vector data is present?

**Comment by XaverKlemenschits** [comment]
Fixed in #59
