### ISSUE TITLE
Remove windows specific step in setup.py for moving *.pyd files

### ISSUE THREAD

**Issue by yozoon** [ViennaTools/ViennaLS#94]
As mentioned in PR #93:
_At the moment there is a separate step in the setup.py script for the windows platform which moves the viennaXs.*.pyd files explicitly. This is a workaround for the fact that the target generated by pybind11_add_module seems to completely ignore the LIBRARY_OUTPUT_DIRECTORY and RUNTIME_OUTPUT_DIRECTORY variables on windows, whereas on linux and macOS, the output artifacts are moved to the proper location by cmake automatically (as specified by LIBRARY_OUTPUT_DIRECTORY). So this is definitely something that needs to be investigated further, but at the moment the workaround should suffice._

Thus in the future it would be nice if we could figure out which CMake target variables need to be changed such that the *.pyd files are automatically generated in the _viennls2d/_ and _viennals3d/_ folders, like on Linux or macOS.

**Comment by Curve** [comment]
This is now solved as we use scikit build
