### ISSUE TITLE
Idea: Use vtk python package instead of linking against vtk for ViennaLS python bindings

### ISSUE THREAD

**Issue by yozoon** [ViennaTools/ViennaLS#95]
Currently the compiled Python modules assume that the shared libraries of vtk remain at the same location as they were during the compilation for as long as the ViennaLS python package is installed. On Linux and macOS the location of the shared vtk libraries are automatically loaded by the runtime linker with the help of the _rpath_ embedded in the compiled python modules. On windows the init script in the python package root takes care of setting up the dll directory using the path that was present at compile time.

## The Problem
If the ViennaLS python bindings are installed in the _site-packages_ directory (as is the case with _pip install ._) the shared libraries must remain at the same location (or at least at a location which the runtime linker knows about) for the python bindings to work. On Linux and macOS this is easily fulfilled if a system wide installation of vtk is present, since its shared libraries are automatically found in the system LD_LIBRARY_PATH and remain at the same system-wide library directory, even if they are updated. But when vtk is built from source by our project, its shared libraries reside in the _dependencies/Install/vtk_external/lib_ folder of the project root. In this case the python package only works as long as the dependencies directory remains at the same place. 

## Possible Solutions
Now there are a few possible ways to deal with this limitation:
1. Install the compiled vtk shared libraries alongside the python package in the site-packages directory (e.g. in a ViennaLS.libs subfolder or something similar).
2. Statically link the vtk libraries into the python bindings
3. Use the shared libraries of the vtk python package

__Option 1__ would theoretically work, but it requires quite a bit of modifications in the externalproject setup in the external/upstream/vtk/CMakeLists.txt file.
__Option 2__ does work (I tested this on Linux), but it's not really elegant, since we would have to do this step for both, the viennals2d and viennals3d package, which leads to unnecessary bloat of our python package.

Both of these options complicate things with regards to the python bindings of ViennaPS, which also require VTK during compilation (since it's using ViennaLS headers which internally include vtk header files). Thus in the first option we would have to at least also include the vtk headers in the package, such that the ViennaPS build can access them and link against the libraries in the site-package directory. The second option cannot easily be used that way, since we would also need the static vtk libraries, which would not be included in the python package. In the second option there also remains the question whether the generated vtk objects would even be compatible between the ViennaLS and ViennaPS python bindings, and at that point we would have four instances of the same vtk library objects linked into viennals2d, viennals3d, viennaps2d and viennaps3d, leading to even more unnecessary bloat.

__Option 3__ comes with some grave limitations: even though the vtk python package does include the shared libraries of vtk alongside the python bindings, it does not ship with the headers. Thus we cannot easily link against the included shared libraries. But if a solution were to be found, we could negate the need for compiling vtk ourselves, and simply use the pre-built vtk package. This leads me to my idea:

## The Idea
Instead of building the viennals python package with vtk support enabled, we set VIENNALS_USE_VTK=OFF. Thus we do not need to link against any vtk library during compile time, nor do we need any vtk header files. To still retain the option to write to- and read from vtk file formats like *.vtp and *.vtu we could implement this functionality in python instead. The current setup of the viennals python package allows for adding additional python-only components to the package, since I wrapped the python bindings that are generated by pybind11 in a python package (the __init__.py file includes the internal _viennalsXd library, which is the one generated by pybind11). We can therefore add arbitrary additional python code alongside our bindings to the package, as long as it is included in the __init__.py file of the package. For vtk file format support, we could implement the lsVTKWriter and lsVTKReader using our python binding and the vtk python bindings. Thus we would generate a vtkPolyData instance from a vls.lsMesh in python and vice-versa for the lsVTKReader.
This would also require some substantial changes to ViennaPS, since it is currently assuming that vtk is available, but since it follows the same python package structure, we could also try to implement this functionality similarly to viennals using the vtk python package.

**Comment by Curve** [comment]
Option 3. is now implemented by 8cf241b :)
